services:
  - type: web
    name: topex-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        sync: false
      - key: JWT_ACCESS_SECRET
        sync: false
      - key: JWT_REFRESH_SECRET
        sync: false
      - key: JWT_ACCESS_EXPIRE
        value: 15m
      - key: JWT_REFRESH_EXPIRE
        value: 7d
      - key: CLIENT_URL
        value: https://topextexnikum.uz
      - key: MAX_FILE_SIZE
        value: 26214400
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: ADMIN_NAME
        value: Super Admin

